version: '3.7'
services: 
    eureka-server:
        image: eureka-server
        ports: 
            - "8761:8761"
        networks: 
            - app-network
    
    
    coupon-service:
        image: coupon-service
        ports: 
            - "5200:5200"
        environment: 
            EUREKA_HOST: eureka-server
        depends_on: 
            - eureka-server
        networks: 
            - app-network

  

networks: 
    app-network:
